import React, { useState, useEffect } from 'react'
import Layout from '../components/Layout'
import ReportSidebar from '../components/ReportSidebar'
import './PreviousReports.css'

const PreviousReports = () => {
  const [reports, setReports] = useState([])
  const [searchTerm, setSearchTerm] = useState('')
  const [selectedReport, setSelectedReport] = useState(null)
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(null)
  const [showSuccessMessage, setShowSuccessMessage] = useState('')
  const [showErrorMessage, setShowErrorMessage] = useState('')

  useEffect(() => {
    const savedReports = JSON.parse(localStorage.getItem('medicalReports') || '[]')
    setReports(savedReports)
  }, [])

  const filteredReports = reports.filter(report => {
    return report.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
           report.type.toLowerCase().includes(searchTerm.toLowerCase())
  })

  const handleViewReport = (report) => {
    setSelectedReport(report)
  }

  const closeModal = () => {
    setSelectedReport(null)
  }

  const handleDownload = (report) => {
    try {
      let content = '';
      let fileName = '';
      let fileType = '';
      
      if (report.fileUrl) {
        fetch(report.fileUrl)
          .then(response => response.blob())
          .then(blob => {
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = report.fileName;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);
            setShowSuccessMessage(`Downloading ${report.fileName}...`);
            setTimeout(() => setShowSuccessMessage(''), 3000);
          })
          .catch(() => {
            downloadAsText(report);
          });
      } else {
        downloadAsText(report);
      }
    } catch (error) {
      setShowErrorMessage('Failed to download report. Please try again.');
      setTimeout(() => setShowErrorMessage(''), 3000);
    }
  };

  const downloadAsText = (report) => {
    const analysis = getSafeAnalysis(report);
    const content = `
HEALTHMATE MEDICAL REPORT
========================
Report Name: ${report.title}
File Name: ${report.fileName}
Date Uploaded: ${report.date}
Report Type: ${report.type}

AI ANALYSIS SUMMARY
------------------
${analysis.summary}

KEY FINDINGS
------------
${analysis.findings.map(f => `• ${f}`).join('\n')}

RECOMMENDATIONS
---------------
${analysis.recommendations.map(r => `• ${r}`).join('\n')}

HEALTH INSIGHTS
---------------
${analysis.insights}

---
Generated by HealthMate AI
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.replace(/[^a-z0-9]/gi, '_')}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    setShowSuccessMessage(`Downloaded ${report.title} report successfully!`);
    setTimeout(() => setShowSuccessMessage(''), 3000);
  };

  const handleDeleteClick = (reportId) => {
    setShowDeleteConfirm(reportId)
  }

  const confirmDelete = (reportId) => {
    const updatedReports = reports.filter(report => report.id !== reportId)
    setReports(updatedReports)
    localStorage.setItem('medicalReports', JSON.stringify(updatedReports))
    setShowDeleteConfirm(null)
    
    if (selectedReport && selectedReport.id === reportId) {
      setSelectedReport(null)
    }
    
    setShowSuccessMessage('Report deleted successfully!')
    setTimeout(() => setShowSuccessMessage(''), 3000)
  }

  const cancelDelete = () => {
    setShowDeleteConfirm(null)
  }

  const getSafeAnalysis = (report) => {
    return {
      summary: report.aiAnalysis?.summary || 'Analysis in progress. Please check back later.',
      findings: report.aiAnalysis?.findings || ['No findings available yet'],
      recommendations: report.aiAnalysis?.recommendations || ['Please consult with your doctor for personalized advice'],
      insights: report.aiAnalysis?.insights || 'Stay healthy with regular checkups'
    };
  };

  return (
    <Layout>
      <div className="previous-reports-page">
        <div className="reports-layout">
          <ReportSidebar />
          <div className="reports-container">
            <div className="reports-header">
              <h1>Previous Reports</h1>
              <p>View all your uploaded medical reports with AI analysis</p>
            </div>

            {showSuccessMessage && (
              <div className="success-message">
                ✓ {showSuccessMessage}
              </div>
            )}
            {showErrorMessage && (
              <div className="error-message">
                ⚠️ {showErrorMessage}
              </div>
            )}

            <div className="reports-controls">
              <div className="search-bar">
                <input 
                  type="text" 
                  placeholder="Search by report name or type..." 
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </div>
            </div>

            {reports.length === 0 ? (
              <div className="no-reports">
                <p>No reports uploaded yet. Go to Report Dashboard to upload your first report.</p>
              </div>
            ) : (
              <div className="reports-table">
                <div className="table-header">
                  <span>Report Name</span>
                  <span>Date</span>
                  <span>Type</span>
                  <span>Action</span>
                </div>
                <div className="table-body">
                  {filteredReports.map(report => (
                    <div className="table-row" key={report.id}>
                      <span className="report-title">{report.title}</span>
                      <span>{report.date}</span>
                      <span>{report.type}</span>
                      <div className="action-buttons">
                        <button className="view-btn" onClick={() => handleViewReport(report)}>
                          View
                        </button>
                        <button className="delete-btn" onClick={() => handleDeleteClick(report.id)}>
                          🗑️ Delete
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {filteredReports.length === 0 && reports.length > 0 && (
              <div className="no-reports">
                <p>No reports found matching "{searchTerm}".</p>
              </div>
            )}

            {showDeleteConfirm && (
              <div className="report-modal-overlay" onClick={cancelDelete}>
                <div className="confirm-modal" onClick={(e) => e.stopPropagation()}>
                  <div className="confirm-modal-header">
                    <span className="confirm-icon">🗑️</span>
                    <h3>Delete Report</h3>
                  </div>
                  <div className="confirm-modal-body">
                    <p>Are you sure you want to delete this report?</p>
                    <p className="confirm-warning">This action cannot be undone.</p>
                  </div>
                  <div className="confirm-modal-footer">
                    <button className="confirm-yes" onClick={() => confirmDelete(showDeleteConfirm)}>
                      Yes, Delete
                    </button>
                    <button className="confirm-no" onClick={cancelDelete}>
                      Cancel
                    </button>
                  </div>
                </div>
              </div>
            )}

            {selectedReport && (
              <div className="report-modal-overlay" onClick={closeModal}>
                <div className="report-modal" onClick={(e) => e.stopPropagation()}>
                  <div className="modal-header">
                    <h2>{selectedReport.title}</h2>
                    <button className="close-btn" onClick={closeModal}>×</button>
                  </div>
                  <div className="modal-body">
                    <div className="report-detail">
                      <label>File Name:</label>
                      <span>{selectedReport.fileName}</span>
                    </div>
                    <div className="report-detail">
                      <label>Date Uploaded:</label>
                      <span>{selectedReport.date}</span>
                    </div>
                    <div className="report-detail">
                      <label>Report Type:</label>
                      <span>{selectedReport.type}</span>
                    </div>
                    
                    {(() => {
                      const analysis = getSafeAnalysis(selectedReport);
                      return (
                        <>
                          <div className="report-detail ai-section">
                            <label>🤖 AI Summary:</label>
                            <p>{analysis.summary}</p>
                          </div>
                          
                          <div className="report-detail ai-section">
                            <label>🔍 Key Findings:</label>
                            <ul>
                              {analysis.findings.map((finding, idx) => (
                                <li key={idx}>{finding}</li>
                              ))}
                            </ul>
                          </div>
                          
                          <div className="report-detail ai-section">
                            <label>💡 Recommendations:</label>
                            <ul>
                              {analysis.recommendations.map((rec, idx) => (
                                <li key={idx}>{rec}</li>
                              ))}
                            </ul>
                          </div>
                          
                          <div className="report-detail ai-section">
                            <label>✨ Health Insight:</label>
                            <p>{analysis.insights}</p>
                          </div>
                        </>
                      );
                    })()}
                  </div>
                  <div className="modal-footer">
                    <button className="download-btn" onClick={() => handleDownload(selectedReport)}>
                      📥 Download Report
                    </button>
                    <button className="delete-btn-modal" onClick={() => handleDeleteClick(selectedReport.id)}>
                      🗑️ Delete
                    </button>
                    <button className="close-modal-btn" onClick={closeModal}>
                      Close
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default PreviousReports;